### ISSUE TITLE
Allow null in Arrays

### ISSUE THREAD

**Issue by carlos22** [krasimir/absurd#104]
Absurd stops processing an array if there is a null/undefined value in it. Is it possible to just ignore undefined/null values?

Example: 

``` js
    body: {
        span: [{ width: '3px'}, null, {height: '3px'}]
    }
```

http://jsbin.com/barubofewiqi/1/edit

``` css
body span {
  width: 3px;
}
```

The `height` is missing here.

Expected Output:

``` css
body span {
  width: 3px;
  height: 3px;
}
```

Yeah you could ask why I want to put nulls in the array. Good Question, but we generate the json object (with some diffing and stuff), so there are cases where a null can appear. This is also fixable before we add the object to absurd. But I think absurd should not stop generating css after null values, should it?
