### ISSUE TITLE
Issue with -webkit-line-clamp

### ISSUE THREAD

**Issue by renatoi** [krasimir/absurd#118]
Proprietary `-webkit-line-clamp` property is giving wrong/broken result in the latest Absurd version, it was working fine before. Is there an option to disable any smart processing Absurd is trying to do with my properties and instead just output what I pass?

```js
'.test': {
    '-webkit-line-clamp': 3
}
```

is producing:

```css
.test {
   webkit-line-clamp: 3;
  -webkit-webkit-line-clamp: 3;
  -moz-webkit-line-clamp: 3;
  -ms-webkit-line-clamp: 3;
  -o-webkit-line-clamp: 3;
}
```
