### ISSUE TITLE
.compile to/should support string compilation?

### ISSUE THREAD

**Issue by tunnckoCore** [krasimir/absurd#119]
How to compile from given CSS string?

```css
body {
  cf: 'all';
  p {
    cf: 'before';
  }
  section {
    cf: 'after';
  }
}
.content {
  p {
    moveto: '10/20/30';
  },
  .animation {
    animate: 'fadeInLeftBig';
    fl: 'right';
  }
}
```
it seems that there's no such feature and also the api is not so node-way-friendly
like here `api.compile(function(){}, {minify: true})`, which can be used to compile synchronously.

move all callbacks to the end. it is hard job to promisify the api.
