### ISSUE TITLE
Implement concatenate & nested selector

### ISSUE THREAD

**Issue by smirea** [krasimir/absurd#16]
if you want to achieve the following, you have to write a rule for `'a': { ... }` and a separate rule for `'a.fancy': {}` which is not ideal given that you should be able to nest these:

``` css
a { color: red; }
a:hover { color: blue; }
a.fancy { color: green; }
```

one solution would be to have it LESS-style using the `&` operator:

``` js
{
  a: {
    color: 'red',
    ':hover': { color: 'blue', }
    '&.fancy': { color: 'green', }
  }
}
```
