### ISSUE TITLE
Nested objects inside array don't work

### ISSUE THREAD

**Issue by gaearon** [krasimir/absurd#25]
Hi, would you please take a look?

``` javascript
api.add({
    body: [{
        width: '80px'
    }, {
        span: {
            display: 'inline'
        }
    }]
});
```

gives

``` css
body {
  width: 80px;
  span: [object Object];
}
body span {
  display: inline;
}
```

You seem to allow arrays, but nested objects inside arrays don't work.
