### ISSUE TITLE
Nested comma selectors don't work

### ISSUE THREAD

**Issue by gaearon** [krasimir/absurd#26]
Hi! Running

``` javascript
api.add({
  "p, span": {
    "b, i": {
       "font-size": '20px'
    }
  }
});
```

gives me

``` css
p, span b, i {
  font-size: 20px;
}
```

which is wrong.

(Should be

``` css
p b, p i, span b, span i {
  font-size: 20px;
}
```

)
