### ISSUE TITLE
Media queries + multiple definitions get compiled inefficiently

### ISSUE THREAD

**Issue by smirea** [krasimir/absurd#32]
If you have in the online compiler:

``` javascript
api.add({
    '@media screen and (max-width: 767px)': {
        a: { color:'red', },
        div: { color:'blue', },
        '.some-class': { color:'green' },
    }
});
```

it gets compiled to:

``` css
@media screen and (max-width: 767px) a {
  color: red;
}
@media screen and (max-width: 767px) div {
  color: blue;
}
@media screen and (max-width: 767px) .some-class {
  color: green;
}
```

Which is not wrong per say, but it would be much better for readability and compression if it would be compiled as:

``` css
@media screen and (max-width: 767px) {
  a { color: red; }
  div { color: blue; }
  .some-class { color: green; }
}
```

In other words, don't prefix the media query to all sub-selectors as it can simply work as a closure
