### ISSUE TITLE
Multiple selectors per rule overwrite all individual selectors

### ISSUE THREAD

**Issue by smirea** [krasimir/absurd#33]
In the online demo, adding this:

``` javascript
api.add({
    'html, body': { color:'red', },
    'body': { background:'blue', },
    'html': { background:'pink', },
});
```

results in this:

``` css
body, html {
  color: red;
}
```

overwriting the individual body and html blocks. It should be compiled to this:

``` css
body, html { color: red; }
body: { background: blue; }
html: { background: pink; }
```
