### ISSUE TITLE
Wrong handling of Array of Objects in Comma Separated Nested-Selectors

### ISSUE THREAD

**Issue by carlos22** [krasimir/absurd#38]
Modified Demo: http://krasimir.github.io/absurd/?demo=5

``` js
// single value
api.storage("fontsize", "16px");
// multiple values
api.storage({
    color: "red",
    theme: function(color) {
        return {
            color: color,
            background: api.lighten(color, 50)
        }
    }
});
api.add({
    body: {
        background: api.storage("color"),
        "section a, section div": [
            api.storage("theme")("#999"),
            { marginTop: "20px" },
            { fontSize: api.storage("fontsize") }
        ]
    }
});
```

Result

``` css
body {
  background: red;
}
body section a 0, body section div 0 {
  background: #e6e6e6;
  color: #999;
}
body section a 1, body section div 1 {
  margin-top: 20px;
}
body section a 2, body section div 2 {
  font-size: 16px;
}
```

Expected Result

``` css
body {
  background: red;
}
body section a, body section div {
  background: #e6e6e6;
  color: #999;
  margin-top: 20px;
  font-size: 16px;
}
```
