### ISSUE TITLE
Plugins in Arrays generate invalid CSS properties.

### ISSUE THREAD

**Issue by carlos22** [krasimir/absurd#39]
``` js
api.plugin("plugin1", function(api, color) {
    return {
        ":hover": {
            color: color
        }
    };
});

api.plugin("plugin2", function(api, color) {
    return {
        ".myCls": {
            color: color
        }
    };
});


api.add({
    a: [
        {"plugin1": "red"},
        {"plugin2": "green"},
        {"plugin1": "blue"}
    ]
});
```

Result

``` css
a {
  plugin1: blue;
  plugin2: green;
}
a:hover {
  color: blue;
}
a .myCls {
  color: green;
}
```

Expected Result

``` css
a:hover {
  color: blue;
}
a .myCls {
  color: green;
}
```

The first plugin "call" is not written as property: value, but all calls after that.
