### ISSUE TITLE
Parent selector and nested multiple selectors, they loose their nesting context

### ISSUE THREAD

**Issue by carlos22** [krasimir/absurd#41]
Consider:

``` js
api.add({
    body: {
        marginTop: "20px",
        width: "100%"
    },
    header: {
        width: "100%",
        '&, .cls2': {
            color: "red"
        }
    }
});
```

Output

``` css
body {
  margin-top: 20px;
}
body, header {
  width: 100%;
}
header, .cls2 {
  color: red;
}
```

But it should be:

``` css
body {
  margin-top: 20px;
}
body, header {
  width: 100%;
}
header, header .cls2 { /* <-- missing header after comma */
  color: red;
}
```

Tested with 0.2.65
