### ISSUE TITLE
Feature Request: Mark Selector as Prefix-Selector in Nesting

### ISSUE THREAD

**Issue by carlos22** [krasimir/absurd#43]
It would be cool if we could do something like:

``` js
api.add({
    '.test': {
        '.some, .sel': {
            '^html.ie8': {
                color: "#333"
            },
            width: "100%"
        }
    }
});
```

``` css

.test .some, .test .sel {
  width: 100%;
}
html.ie8 .test .some, html.ie8 .test .sel {
  color: #333;
}
```

Normally the html.ie8 would be appended to the current selector chain. But it would be great if we could use a Symbol (like ^, shoud be an otherwise invalid css selector symbol) which turns the append in a prepend (globally)

Example Use Case: IE8 fixes with complex nested selectors (you don't have to copy the whole selector for the fix).
