### ISSUE TITLE
Same CSS Property Multiple Times in One Rule

### ISSUE THREAD

**Issue by carlos22** [krasimir/absurd#44]
CSS allows you to write something like:

``` css
body {
  color: rgb(0,0,0);
  color: rgba(0,0,0,0.5);
}
```

This is a common way to have a rule for both browsers supporting rgba() and browsers that don't (like IE8).

But absurd.js uses the key of JS Objects, which (of course) only support the property once. 

To overcome this limitation we could add a prefix that is just ignored:

``` js
api.add({
    body: {
        color: "rgb(0,0,0)",
        _color: "rgba(0,0,0,0.5)"
    },
});
```

But this relies on the fact that most JS Engines return the object in the same order as specified, which is not guaranteed.

Another solution would be the use of arrays which provide the ordering and objects for the properties:

``` js
api.add({
    body: {
        '&': [{color: "rgb(0,0,0)"},
              {color: "rgba(0,0,0,0.5)"}]
    },
});
```

But this doesn't work, as absurd.js merges them:

``` css
body {
  color: rgba(0,0,0,0.5);
}
```
