### ISSUE TITLE
Check if object is plain object before evaluating it

### ISSUE THREAD

**Issue by smirea** [krasimir/absurd#52]
It would be nice if absurd would check if the values are actually object literals before proceeding to consider them as a collection of properties. (aka check `if (obj.toString() === '[object Object]') {}` or something similar)

This would be extremely helpful in allowing you to create custom classes which evaluate to strings. For example, I want to implement a `px` class which at its core just appends 'px' to any number, but you can also add px-els:

``` javascript
var px = function (value) {
  var tmp = function () {};
  tmp.prototype = {
    val: value,
    add: function (obj) { 
      this.val += (typeof obj == 'number' ? obj : obj.val); 
      return this;
    },
    toString: function () { return this.val + 'px'; },
    toJSON: function () { return this.toString(); },
  };
  return new tmp();
};
```

so then I would be able to do things like this in absurd:

``` javascript
var elementSize = 50;
var margin = 10;
return {
  body: { width: px(elementSize).add(margin), },
};
```

and have it be evaluated to:

``` css
body {
  width: 60px;
}
```

Currently it just takes the object and does ungodly things to it and you get stuff like:

``` css
.tag test {
  0: [;
  1: o;
  2: b;
  3: j;
  4: e;
  5: c;
  6: t;
  7:  ;
  8: U;
  9: n;
  10: d;
  11: e;
  12: f;
  13: i;
  14: n;
  15: e;
  16: d;
  17: ];
  to-j-s-o-n: 10px;
}
```
