### ISSUE TITLE
Indent block in media queries

### ISSUE THREAD

**Issue by smirea** [krasimir/absurd#53]
This a a media query block generated by absurd:

``` css
@media (max-width: 930px) {
#productInfo {
  display: block;
  width: auto;
}
#productInfo .content {
  display: none;
}
#productInfo .actions {
  display: none;
}
}
```

it would be much easier to read if its content would be indented once:

``` css
@media (max-width: 930px) {
  #productInfo {
    display: block;
    width: auto;
  }
  #productInfo .content {
    display: none;
  }
  #productInfo .actions {
    display: none;
  }
}
```

so you can clearly see where the media tag ends and what's inside it
