### ISSUE TITLE
combineSelectors:false breaks @font-face

### ISSUE THREAD

**Issue by smirea** [krasimir/absurd#55]
`@font-face` should not be split apart, regardless of anything since it specifies a rule block. I don't know all css special `@` rules, but I'm assuming `font-face` is not the only one affected by this

Example:

``` javascript
api.add({
  '@font-face': {
    fontFamily: 'MuseoSans',
    src: "url('/fonts/Museo Sans/MuseoSans_500.otf')", 
  },

  'body': {
    fontFamily: 'MuseoSans',
    fontSize: '10pt',
  },    
}).compile(function (err, css) { console.log(css) })
```

produces

``` css
@font-face, body {
  font-family: MuseoSans;
}
@font-face {
  src: url('/fonts/Museo Sans/MuseoSans_500.otf');
}
body {
  font-size: 10pt;
}
```
