### ISSUE TITLE
don't overwrite @font-face

### ISSUE THREAD

**Issue by smirea** [krasimir/absurd#56]
similar to #55, multiple `@font-face` should not be overwritten and should be considered two different entities

Example

``` javascript
api.add({
    '@font-face': {
      fontFamily: 'MuseoSans',
      src: "url('/fonts/Museo Sans/MuseoSans_500.otf')", },
  });

  api.add({
    '@font-face': {
      fontFamily: 'MuseoSans',
      fontStyle: 'italic, oblique',
      src: "url('/fonts/Museo Sans/MuseoSans_500_italic.otf')", }
  });
```

wrong output:

``` css
@font-face {
  font-family: MuseoSans;
  src: url('/fonts/Museo Sans/MuseoSans_500_italic.otf');
  font-style: italic, oblique;
}
```
