### ISSUE TITLE
Don't print out empty selectors

### ISSUE THREAD

**Issue by smirea** [krasimir/absurd#58]
There are many cases where selectors end up having no rules (either by not having, or by combining selectors, etc)

Example:

``` javascript
css['.system'] = {
    '&:before': {
      position: 'absolute',
      color: 'red',
      content: 'SS',
    },

    '&-shields': {

    },
  };
```

results in:

``` css
.system {
}
.system:before {
  position: absolute;
  color: red;
  content: SS;
}
.system-shields {
}
```

Printing the empty `.system {}` takes up spaces and has no real effect on the overall result (same for `.system-shields`)
