### ISSUE TITLE
Duplicate Vendor Prefixes If Full Prefixes Are Used

### ISSUE THREAD

**Issue by carlos22** [krasimir/absurd#82]
``` js
var api = Absurd();
api.add({
    header: {
      "-moz-animation-name": "test",
      "-webkit-animation-name": "test"
    }
});

api.compile(function(o, e) { console.log(o, e); });
```

yields to

``` css
header {
  moz-animation-name: test;
  -webkit-moz-animation-name: test;
  -moz-moz-animation-name: test;
  -ms-moz-animation-name: test;
  -o-moz-animation-name: test;
  webkit-animation-name: test;
  -webkit-webkit-animation-name: test;
  -moz-webkit-animation-name: test;
  -ms-webkit-animation-name: test;
  -o-webkit-animation-name: test;
}
```

I know there is a way using `-w-animation-name` but I think using the standard syntax of CSS should not compile to garbage! 

Expected output:

``` css
header {
  -webkit-animation-name: test;
  -moz-animation-name: test;
}
```
