### ISSUE TITLE
Combining selectors shouldn't preserve % tags

### ISSUE THREAD

**Issue by kleinspire** [krasimir/absurd#87]
``` javascript
  api.add({
    '.navigation': {
        color: 'red'
    },
    '.button': {
        width: '20px'
    },
    '%0%.button': {
        color: 'red'
    }

  })
```

Produces:

``` css
.navigation, %0%.button {
  color: red;
}
.button {
  width: 20px;
}
```
