### ISSUE TITLE
@font-face shouldn't be combined

### ISSUE THREAD

**Issue by kleinspire** [krasimir/absurd#89]
``` javascript
  api.add({
    '%1%@font-face': {
      'font-family': '\'Titillium\'',
      src: 'url(\'type/titillium-light-webfont.eot\')',
      'font-style': 'normal'
    },
    '%2%@font-face': {
      'font-family': '\'Titillium\'',
      src: 'url(\'type/titillium-lightitalic-webfont.eot\')',
      'font-style': 'italic'
    }
  });
```

Produces:

``` css
@font-face, @font-face {
  font-family: 'Titillium';
}
@font-face {
  src: url('type/titillium-light-webfont.eot');
  font-style: normal;
}
@font-face {
  src: url('type/titillium-lightitalic-webfont.eot');
  font-style: italic;
}
```

with 3+ @font-face rules, absurd ends up in an infinite loop somewhere:

``` javascript
  api.add({
    '%1%@font-face': {
      'font-family': '\'Titillium\'',
      src: 'url(\'type/titillium-light-webfont.eot\')',
      'font-style': 'normal'
    },
    '%2%@font-face': {
      'font-family': '\'Titillium\'',
      src: 'url(\'type/titillium-lightitalic-webfont.eot\')',
      'font-style': 'italic'
    },
    '%3%@font-face': {
      'font-family': '\'Titillium\'',
      src: 'url(\'type/titillium-semibold-webfont.eot\')',
      'font-weight': '600',
      'font-style': 'normal'
    }
  });
```
