### ISSUE TITLE
Selectors with browser prefixes should only be combined with selectors with the same prefix

### ISSUE THREAD

**Issue by kleinspire** [krasimir/absurd#96]
``` javascript
api.add({
  'input[type="search"]::-webkit-search-cancel-button': { display: 'none' },
  'input[type="search"]::-webkit-search-results-button': { display: 'none' },
  '.HiddenCheckbox': { display: 'none' }
});
```

compiles to:

``` css
input[type="search"]::-webkit-search-cancel-button, input[type="search"]::-webkit-search-results-button, .HiddenCheckbox {
  display: none;
}
```

Some browsers are unable to read the display:none property of .HiddenCheckbox if it is combined with selectors unknown to them.

Ideally, it should compile to:

``` css
input[type="search"]::-webkit-search-cancel-button, input[type="search"]::-webkit-search-results-button {
  display: none;
}
.HiddenCheckbox {
  display: none;
}
```
